package momento:functions@1.0.0;

world host {
    include momento:host/imports@1.0.0;

    import cache-scalar;
    import permission-messages;
    import token;
    import topic;
}

world web-function {
    include host;

    export guest-function-web;
    import web-function-support;
}

world spawn-function {
    include host;

    export guest-function-spawn;
}
